tDD（テスト駆動開発）でコードを書いてみる
gn-t-k/PrAhaChallengeTasks pull request #17
Opened 2021-02-09 14:46 UTC by gn-t-k

2021-02-20 10:06 UTC, AwataKyosuke requested changes
何点か気になったところにコメントしました！
自分の環境が原因だと思いますが、テストやスクリプトを実際に動かせていないので、想像で書いている部分もありますが、ご容赦ください:bow:
また、コメントの中にはTDDとは直接関係ないこともあるので、もし不要でしたらスルーしてください！

2021-02-20 10:06 UTC, AwataKyosuke commented on TDD（テスト駆動開発）でコードを書いてみる/src/script.js
> +const operation = getOperation(program.args);
`getOperation`が`add~devide`以外なら例外を投げるような作りにして、処理を終わらせた方がいいのかなと思いました！
理由としては、operationがadd~devide以外なら、numbersの取得は不要になるので、無駄な処理が実行されるなと感じたためです。

2021-02-20 10:06 UTC, AwataKyosuke commented on TDD（テスト駆動開発）でコードを書いてみる/src/script.js
> +const numbers = getNumbers(program.args.slice(1));
こちらも同様に、不正な値の場合は例外を投げるような作りにして、処理を終わらせた方がいいのかなと思いおました！
そうしなければ、`getNumbers`の戻り値が文字列の場合に`add`などが使用している`reduce`で想定外のエラーが起きるのではないでしょうか？

2021-02-20 10:18 UTC, gn-t-k commented on TDD（テスト駆動開発）でコードを書いてみる/【回答】TDD（テスト駆動開発）でコードを書いてみる.md
> +yarn test
なるほどです！
`yarn install --frozen-lockfile`ではなく、`yarn`だけだとどうでしょうか…？
お手数おかけして恐縮なのですが、`yarn.lock`と`node_modules`を一度削除してから確認してみていただけますか？

2021-02-23 15:04 UTC, AwataKyosuke commented on TDD（テスト駆動開発）でコードを書いてみる/【回答】TDD（テスト駆動開発）でコードを書いてみる.md
> +yarn test
すみません、やっぱり実行できずでした...:scream:

2021-02-23 15:08 UTC, AwataKyosuke approved these changes
一旦テストとスクリプトの実行は諦めます！LGTMです！

2021-02-24 00:38 UTC, gn-t-k commented on TDD（テスト駆動開発）でコードを書いてみる/【回答】TDD（テスト駆動開発）でコードを書いてみる.md
> +yarn test
😱 
ちなみにどんなエラーですか？

2021-03-03 05:55 UTC, ampersand-github commented
LGBM

2021-03-03 05:55 UTC, merged