データベース設計のアンチパターンを学ぶ3
gn-t-k/PrAhaChallengeTasks pull request #27
Opened 2021-03-20 07:51 UTC by gn-t-k

回答mdはこちら→[03_データベース/08_データベース設計のアンチパターンを学ぶ/【回答】データベース設計のアンチパターンを学ぶ3.md]()

回答の内容に不足などありましたらご指摘お願いします。

以下のchrome拡張をインストールすると、プレビューでER図が図示されて見やすくなります。
https://chrome.google.com/webstore/detail/pegmatite/jegkfbnfbfnohncpcfcimepibmhlkldo

2021-03-20 08:27 UTC, AwataKyosuke requested changes

2021-03-20 08:27 UTC, AwataKyosuke commented on 03_データベース/08_データベース設計のアンチパターンを学ぶ/【回答】データベース設計のアンチパターンを学ぶ3.md
> +Commentに`book_type`を設ける。`manga`や`novel`といった種別を設定することで、何に対するコメントなのか識別できる。
これはSQLアンチパターンに出てくるポリモーフィック関連に該当し、良くない設計とされています！
https://qiita.com/dai329/items/1db8fbe37f43a465d801

今回のケースだと、アンチパターンを許容するメリットがあまり見当たらないので、避けた方が無難かと思います。

2021-03-20 08:27 UTC, AwataKyosuke commented on 03_データベース/08_データベース設計のアンチパターンを学ぶ/【回答】データベース設計のアンチパターンを学ぶ3.md
> +一体にするの、アリなのか。既に動いているサービスを改修するというシチュエーションを考えると、アプリケーション側の修正がえげつなくなりそう。
すでに動いていると仮定すれば、確かに修正はえげつないかもしれないですね、、。
ただ、NovelとManga以外に、参考書やレシピ本など他のジャンルの本を増やしたくなった場合に、テーブルを新規追加する必要が出てくるので、自分は一体にする方法を取りました！

2021-03-21 01:36 UTC, ampersand-github commented on 03_データベース/08_データベース設計のアンチパターンを学ぶ/【回答】データベース設計のアンチパターンを学ぶ3.md
> +一体にするの、アリなのか。既に動いているサービスを改修するというシチュエーションを考えると、アプリケーション側の修正がえげつなくなりそう。
テーブルを新規追加するのは仕方ないと思います。
それよりもアンチパターンを避けることが重要？かなと思います。

2021-03-21 01:50 UTC, ampersand-github reviewed
lgtm

2021-03-21 01:50 UTC, ampersand-github commented on 03_データベース/08_データベース設計のアンチパターンを学ぶ/【回答】データベース設計のアンチパターンを学ぶ3.md
> +    - マンガは`m_001`、小説は`n_001`とかにする
idに意味が付与されてしまうのはよくないです。
あとで業務上の都合で接頭辞が変更された場合修正が大変です。

2021-03-21 01:50 UTC, ampersand-github commented on 03_データベース/08_データベース設計のアンチパターンを学ぶ/【回答】データベース設計のアンチパターンを学ぶ3.md
> +  book_type
book_type用のテーブルを作ってそこと外部キーでつなげると良いと思います。

2021-03-21 01:50 UTC, merged