【参加者をペアから削除】プラハチャレンジをDDDで実装してみる
gn-t-k/PrAhaChallengeTasks pull request #68
Opened 2021-07-03 12:43 UTC by gn-t-k

## 対応内容

- [ ] 参加者をペアから削除するユースケース実装
  - [x] 実装
  - [ ] テスト
  - [ ] モック

## 見てほしいところ

仕様的に漏れがないかご確認お願いします（ペアなどの合併は実装してないです）（参加者の数が足りなくなるような場合、エラーになります）

2021-07-04 15:38 UTC, AwataKyosuke requested changes
コメントしました！確認お願いします:+1:

2021-07-04 15:38 UTC, AwataKyosuke commented on 04_設計/04_プラハチャレンジをDDDで実装してみる/02_APIサーバ/src/__tests__/usecase/remove-member-from-pair.test.ts
> +    expect(JSON.stringify(teamRepositoryUpdateSpy.mock.calls[0][0])).toEqual(
自分の実装で申し訳ないですが、このあたり参考になるかもです、、！

- [ファクトリもモックしてリポジトリの引数に渡されていることを確認する（今回だとTeamFactoryですかね？）](https://github.com/AwataKyosuke/PrAha_Challenge/blob/main/04_%E8%A8%AD%E8%A8%88/04_%E3%83%97%E3%83%A9%E3%83%8F%E3%83%81%E3%83%A3%E3%83%AC%E3%83%B3%E3%82%B8%E3%82%92DDD%E3%81%A7%E5%AE%9F%E8%A3%85%E3%81%97%E3%81%A6%E3%81%BF%E3%82%8B/source/src/application/pair/remove-participant/remove-participant-usecase.test.ts#L84)
- [愚直にtoEqualで頑張る](https://github.com/AwataKyosuke/PrAha_Challenge/blob/main/04_%E8%A8%AD%E8%A8%88/04_%E3%83%97%E3%83%A9%E3%83%8F%E3%83%81%E3%83%A3%E3%83%AC%E3%83%B3%E3%82%B8%E3%82%92DDD%E3%81%A7%E5%AE%9F%E8%A3%85%E3%81%97%E3%81%A6%E3%81%BF%E3%82%8B/source/src/application/pair/remove-participant/remove-participant-usecase.test.ts#L100)

2021-07-04 15:38 UTC, AwataKyosuke commented on 04_設計/04_プラハチャレンジをDDDで実装してみる/02_APIサーバ/src/usecase/remove-member-from-pair.ts
> +        (member) => member.id.value === props.memberID,
```suggestion
        (member) => member.id.equals(new Identifer(props.memberID),
```
id.valueを使うと内部知識が漏れてしまっているように感じるので、上記のように識別子は識別子として比較する方が良いかと思います！

2021-07-04 15:38 UTC, AwataKyosuke commented on 04_設計/04_プラハチャレンジをDDDで実装してみる/02_APIサーバ/src/usecase/remove-member-from-pair.ts
> +              (member) => member.id.value !== props.memberID,
ここもですね！

2021-07-04 22:54 UTC, gn-t-k commented on 04_設計/04_プラハチャレンジをDDDで実装してみる/02_APIサーバ/src/__tests__/usecase/remove-member-from-pair.test.ts
> +    expect(JSON.stringify(teamRepositoryUpdateSpy.mock.calls[0][0])).toEqual(
いまの実装で factoryをモックしてしまったら、それより前の段階で行ってる処理が意味なくなってしまうので、ウーンとなってやめました、、

2021-07-05 02:59 UTC, AwataKyosuke commented on 04_設計/04_プラハチャレンジをDDDで実装してみる/02_APIサーバ/src/__tests__/usecase/remove-member-from-pair.test.ts
> +    expect(JSON.stringify(teamRepositoryUpdateSpy.mock.calls[0][0])).toEqual(
@gn-t-k 
このユースケースをざっくり言葉で表すと
1. 変更対象のペアが所属するチームを取得する
2. ペアから参加者を減らしてチームを再構築する
3. チームを更新する

こんな感じですかね？

そして、このユースケース独自の処理は、`ペアから参加者を減らして`というところだけだと思うので、それ以外は`正しい引数で別クラスの処理が呼ばれていること`だけ確認すれば良いことになります。
なので、ファクトリをモックしても特段問題はないかな？というのが自分の認識です:eyes:

もし自分がこのユースケースのテストケースを作るなら、以下のように分けるかなと思いました

- チームリポジトリのペアが所属するチームの検索処理が正しい引数で呼ばれていること
- ペアが所属するチームがなければエラーとなること
- チームファクトリが指定の参加者をペアから削除した引数で呼ばれていること
  - リポジトリからの戻り値はスタブで固定されているので、確認は容易（な気がする）
- チームリポジトリのupdateがファクトリの戻り値を引数に渡して呼ばれていること
  - ここのテストをするときはファクトリをモックして適当なチームを返すようにしておく

このようにテストケースを細かく分けてあげれば、リポジトリやファクトリをユースケースが正しく使えていることを問題なくテストできるのではないかと！（意味がなくなってしまう、というのはこういうことを指しているだと勝手に予想しました）

ご参考までに:bow:

2021-07-05 02:59 UTC, AwataKyosuke approved these changes
テストについてコメントを追加しました！LGTMです:+1:

2021-07-05 11:55 UTC, gn-t-k commented on 04_設計/04_プラハチャレンジをDDDで実装してみる/02_APIサーバ/src/__tests__/usecase/remove-member-from-pair.test.ts
> +    expect(JSON.stringify(teamRepositoryUpdateSpy.mock.calls[0][0])).toEqual(
> このようにテストケースを細かく分けてあげれば、リポジトリやファクトリをユースケースが正しく使えていることを問題なくテストできるのではないかと！

たしかにめっちゃおっしゃるとおりだと思いました！！
また、ペアから参加者を減らすことがユースケース独自の処理だというのもそのとおりで、いいかんじのテストがひらめいたので修正しました
ありがとうございます

2021-07-05 11:56 UTC, merged